'' -*- mode: plantuml -*- ''
skinparam componentStyle uml1

skinparam component {
    BorderColor white
    BackgroundColor #000066
    FontColor white
}
skinparam package {
    BorderColor #000066
    BackgroundColor #eeeeff
}
skinparam interface {
    BorderColor #000066
    BackgroundColor #000066
    FontColor #000066
}
skinparam file {
    BorderColor #c0c0c0
    BackgroundColor #808080
    FontColor #000066
}
skinparam  {
   ArrowColor #000066
}
skinparam node {
    BorderColor #000066
    BackgroundColor #eeeeff
}
